#!/bin/bash
export GIT_COMMITTER_DATE="Wed Oct 13 15:23 2020 +0100"
   export GIT_AUTHOR_DATE="Wed Oct 13 15:22 2020 +0100"
git add .
git commit -am " new update to code scripts"
git push origin master

