#!/bin/bash
export GIT_COMMITTER_DATE="Wed Oct 21 1:23 2020 +0100"
   export GIT_AUTHOR_DATE="Wed Oct 21 12:22 2020 +0100"
git add .
git commit -am " new update to code scripts"
git push origin master

