

{{- $prj := .Values.microservice.name -}}
{{- $ing :=  printf "%s-ing" .Values.microservice.name -}}
{{- $env := .Values.global.environment -}}
{{- $srvPort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $ing }}
  labels:
    app: {{ .Values.application.name  }}
    component: {{ $prj }}
    environment: {{ $env }}
{{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
- hosts: localhost
  remote_user: root
  roles:
    - openshift