

{{- $prj := .Values.microservice.name -}}
{{- $ing :=  printf "%s-ing" .Values.microservice.name -}}
{{- $env := .Values.global.environment -}}
{{- $srvPort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $ing }}
  labels:
    app: {{ .Values.application.name  }}
    component: {{ $prj }}
    environment: {{ $env }}
{{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
{{- with .Values.ingress.paths }}
        paths:
{{ toYaml . | indent 8 }}
{{- end -}}---{{- $prj := .Values.microservice.name -}}
{{- $ing :=  printf "%s-ing" .Values.microservice.name -}}
{{- $env := .Values.global.environment -}}
{{- $srvPort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $ing }}
  labels:etadata:
  name: {{ .key }}
type: Opaqueetadata:
  name: {{ .key }}
type: Opaqueetadata:
  name: {{ .key }}
type: OpaqueapiVersion: v1
appVersion: "1.0"
apiVersion: v1
appVersion: "1.0"
description: Helm chart for a JBoss app
name: jboss-as-chart
version: 1.0


echo " installing Terraform"
echo "============================================"

wget https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
sudo apt-get install zip -y
unzip terraform*.zip
sudo mv terraform /usr/local/bin
terraform version

echo " installing Terraform"
echo "============================================"

wget https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
sudo apt-get install zip -y
unzip terraform*.zip
sudo mv terraform /usr/local/bin
terraform version

echo " installing Kube client"
    app: {{ .Values.application.name  }}
    component: {{ $prj }}
    environment: {{ $env }}
{{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
{{- with .Values.ingress.paths }}
        paths:
{{ toYaml . | indent 8 }}
{{- end -}}
- hosts: localhost
  remote_user: root
  roles:
    - openshift