

{{- $prj := .Values.microservice.name -}}
{{- $ing :=  printf "%s-ing" .Values.microservice.name -}}
{{- $env := .Values.global.environment -}}
{{- $srvPort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $ing }}
  labels:
    app: {{ .Values.application.name  }}
    component: {{ $prj }}
    environment: {{ $env }}
{{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
{{- with .Values.ingress.paths }}
        paths:
{{ toYaml . | indent 8 }}
{{- end -}}---{{- $prj := .Values.microservice.name -}}
{{- $ing :=  printf "%s-ing" .Values.microservice.name -}}
{{- $env := .Values.global.environment -}}
{{- $srvPort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $ing }}
  labels:
    app: {{ .Values.application.name  }}
    component: {{ $prj }}
    environment: {{ $env }}
{{- with .Values.ingress.annotations }}
  annotations:
    {{- toY
- hosts: localhost
  remote_user: root
  roles:
    - openshift